# Generated by Django 4.1.4 on 2022-12-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='about',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
        migrations.AddField(
            model_name='employee',
            name='amount',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
